# src/pipeline/alerts.py
# Phase 7: Anomaly alerting — Slack + email
# Run: python -m src.pipeline.alerts

import os
import json
import smtplib
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from dotenv import load_dotenv
from sqlalchemy import text

load_dotenv()


def _get_engine():
    from src.pipeline.ingest import get_engine
    return get_engine()


# ─── SLACK ────────────────────────────────────────────────────────────────────

def send_slack_alert(anomalies: list[dict]) -> None:
    """
    Post an anomaly summary to Slack using Block Kit formatting.

    Parameters
    ----------
    anomalies : list[dict]
        List of anomaly dicts with keys: flag, severity, segment, delta, period.

    Skips silently if SLACK_WEBHOOK_URL is not set.
    """
    webhook_url = os.getenv("SLACK_WEBHOOK_URL")
    if not webhook_url:
        print("  [alerts] SLACK_WEBHOOK_URL not set — skipping Slack alert.")
        return

    from slack_sdk.webhook import WebhookClient

    severity_emoji = {"high": "🔴", "medium": "🟡", "low": "🟢"}

    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"📊 Sales Analytics Alert — {date.today().isoformat()}",
            },
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*{len(anomalies)} anomaly/anomalies detected* requiring attention:",
            },
        },
        {"type": "divider"},
    ]

    for a in anomalies:
        emoji = severity_emoji.get(a["severity"], "⚪")
        blocks.append({
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*Type:* {emoji} {a['flag'].replace('_', ' ').title()}"},
                {"type": "mrkdwn", "text": f"*Severity:* {a['severity'].upper()}"},
                {"type": "mrkdwn", "text": f"*Segment:* {a['segment']}"},
                {"type": "mrkdwn", "text": f"*Period:* {a['period']}"},
                {"type": "mrkdwn", "text": f"*Delta:* {a['delta']:+.2f}"},
            ],
        })
        blocks.append({"type": "divider"})

    client = WebhookClient(webhook_url)
    response = client.send(blocks=blocks)
    if response.status_code == 200:
        print(f"  [alerts] Slack alert sent — {len(anomalies)} anomalies.")
    else:
        print(f"  [alerts] Slack alert failed: {response.status_code} {response.body}")


# ─── EMAIL ────────────────────────────────────────────────────────────────────

def send_email_alert(anomalies: list[dict]) -> None:
    """
    Send an anomaly summary via SMTP (Gmail SSL).

    Skips silently if ALERT_EMAIL_FROM is not set.
    """
    from_addr = os.getenv("ALERT_EMAIL_FROM")
    to_addr = os.getenv("ALERT_EMAIL_TO")
    password = os.getenv("ALERT_EMAIL_PASSWORD")

    if not from_addr:
        print("  [alerts] ALERT_EMAIL_FROM not set — skipping email alert.")
        return

    severity_color = {"high": "#E74C3C", "medium": "#F39C12", "low": "#3498DB"}

    rows_html = ""
    for a in anomalies:
        color = severity_color.get(a["severity"], "#95A5A6")
        rows_html += f"""
        <tr>
            <td style="padding:8px;border:1px solid #ddd">{a['flag'].replace('_', ' ').title()}</td>
            <td style="padding:8px;border:1px solid #ddd;color:{color};font-weight:bold">
                {a['severity'].upper()}
            </td>
            <td style="padding:8px;border:1px solid #ddd">{a['segment']}</td>
            <td style="padding:8px;border:1px solid #ddd">{a['period']}</td>
            <td style="padding:8px;border:1px solid #ddd">{a['delta']:+.2f}</td>
        </tr>"""

    html_body = f"""
    <html><body style="font-family:Arial,sans-serif;color:#333">
        <h2 style="color:#2C3E50">📊 Sales Analytics Alert — {date.today().isoformat()}</h2>
        <p><strong>{len(anomalies)} anomaly/anomalies</strong> detected requiring attention:</p>
        <table style="border-collapse:collapse;width:100%;max-width:700px">
            <thead>
                <tr style="background:#2C3E50;color:white">
                    <th style="padding:10px;text-align:left">Type</th>
                    <th style="padding:10px;text-align:left">Severity</th>
                    <th style="padding:10px;text-align:left">Segment</th>
                    <th style="padding:10px;text-align:left">Period</th>
                    <th style="padding:10px;text-align:left">Delta</th>
                </tr>
            </thead>
            <tbody>{rows_html}</tbody>
        </table>
        <p style="color:#7F8C8D;margin-top:20px;font-size:12px">
            Generated by Sales Analytics Copilot
        </p>
    </body></html>
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"[Sales Copilot] {len(anomalies)} Anomalies Detected — {date.today().isoformat()}"
    msg["From"] = from_addr
    msg["To"] = to_addr
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(from_addr, password)
            server.sendmail(from_addr, to_addr, msg.as_string())
        print(f"  [alerts] Email alert sent to {to_addr}.")
    except Exception as e:
        print(f"  [alerts] Email alert failed: {e}")


# ─── MAIN RUNNER ──────────────────────────────────────────────────────────────

def run_alerts() -> None:
    """
    Detect anomalies and dispatch Slack + email alerts for high/medium severity.
    Updates run_log with the anomaly count.
    """
    from src.analytics.anomalies import detect_anomalies

    print("\n[alerts] Running anomaly detection...")
    all_anomalies = detect_anomalies()
    alertable = [a for a in all_anomalies if a["severity"] in ("high", "medium")]

    print(f"[alerts] {len(all_anomalies)} total anomalies, {len(alertable)} high/medium.")

    if not alertable:
        print("[alerts] No high/medium anomalies — no alerts sent.")
    else:
        send_slack_alert(alertable)
        send_email_alert(alertable)

    # Update run_log with anomaly count
    try:
        engine = _get_engine()
        with engine.connect() as conn:
            conn.execute(
                text("""
                    UPDATE run_log SET anomalies_found = :n
                    WHERE run_id = (SELECT MAX(run_id) FROM run_log WHERE status = 'success')
                """),
                {"n": len(alertable)},
            )
            conn.commit()
        print("[alerts] run_log updated.")
    except Exception as e:
        print(f"[alerts] run_log update failed: {e}")


if __name__ == "__main__":
    run_alerts()
